name: WorldCitizen
favicon: null
layout_spectrum: 0.7292
typography_spectrum: 0.86139
title: Networking For Peace - Where seeking minds meet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#385800'
    - '#212121'
    - '#c19d65'
    - '#b4da37'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
